// <auto-generated />
namespace YipYip22.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class again2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(again2));
        
        string IMigrationMetadata.Id
        {
            get { return "202008071519495_again2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
