// <auto-generated />
namespace YipYip22.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class tookIcolectooutofowner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tookIcolectooutofowner));
        
        string IMigrationMetadata.Id
        {
            get { return "202008071439268_took Icolecto outof owner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
